### ISSUE TITLE
Question about Dataset and Training

### ISSUE THREAD

**Issue by Shoawen0213** [juanmc2005/StreamingSpeakerDiarization#33]
Hello! it's me again, sorry for bothering...
I have several problems
I've seen [pyannote-audio](https://github.com/pyannote/pyannote-audio/tree/develop) for reference. 
1)If i want to train (fine-tune) my own model, i should follow [training_a_model.ipynb](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/training_a_model.ipynb), am i right? 
If it's correct, the difference between the "models" part and "Pipelines" parts is that the pipelines contain all models needed, like VAD, OSD,... So, if I want to train my own model, do I need to do both these parts?
2) In your project, does the AMI dataset contain "only_words" and "word_and_vocalsounds"? I ask this question just because in [training_a_model.ipynb](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/training_a_model.ipynb), it only uses "only_words" part, I'm trying to figure out how to use the whole datasets...
3) How to get DIHARD II and III datasets? I've tried to google them, but it guides me to their official website...
4) If I get DIHARD and VoxConverse dataset (.wav file), seems that I need to follow the way same as AMI, like generating database.yml on my own, am I right? If it's correct, I'm confused about how to get the correct rttm files for training

Again, thanks for your awesome project!! 
It's helped a lot due to I'm a rookie in this domain without any mentor to ask...
Sorry for all those stupid questions...
Looking forward to your reply...

**Comment by juanmc2005** [comment]
Hello @Shoawen0213,

1) To train your own segmentation model you don't need a pipeline because the model already takes care of VAD and OSD. However, it cannot replace the clustering module to do diarization on more than 5s of audio. In that case you either use what pyannote provides for offline speaker tracking (not really sure what that is at the moment, @hbredin you might know better) or you plug in your newly trained model into diart to make it online. Note that you don't need clustering to train the segmentation.

2) I used AMI only_words in this project.

3) @hbredin you may know the answer to this one better than me.

4) Yes you have to set them up with pyannote.database to fine-tune or train your model from scratch. The rttms should be available with each dataset.

**Comment by Shoawen0213** [comment]
Hi ! @juanmc2005
thanks for your reply to those questions! 
I thought you wouldn't reply because I'm so annoying... QQ
I will try by following your hints!!
