### ISSUE TITLE
Question about produce the system

### ISSUE THREAD

**Issue by Shoawen0213** [juanmc2005/StreamingSpeakerDiarization#52]
Hi @juanmc2005 ! it's me again, sorry for bothering...
I have read #14  and I have several problems...
in that issue, you said that training the whole system is divided into two steps:
- pre-train the segmentation and speaker embedding models
- fine-tune hyper-parameters tau, rho and delta

I'm still not sure how to fulfill the first step
If my case is going to fine-tune with my own dataset _(although i'm still trying how to fulfill the database.yaml)_ or just fine-tuning with AMI database. 
Seems that [here](https://huggingface.co/pyannote/segmentation) and [here](https://huggingface.co/pyannote/embedding) only tell how to use, but not how to train it. 
When i trace the pipeline.py code, I saw
`segmentation: PipelineModel = "pyannote/segmentation"`
 `embedding: PipelineModel = "pyannote/embedding"
`
So, i can replace the fine-tune model into those model here or other place?
If the answer is yes, when i try to replace the segmentation model like
`segmentation: PipelineModel = Model.from_pretrained('./version_0/checkpoints/epoch=49-step=90749.ckpt')`
I notice that it still running with `segmentation: PipelineModel = "pyannote/segmentation` because when i comment this line, `python -m diart.demo` is still working...it make me confused QAQ
BTW how and do i need to fine-tune the speaker embedding models?

for the second step, is there any way to process them?

best regards

**Comment by juanmc2005** [comment]
Hi @Shoawen0213, here's a [pyannote.audio tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/training_a_model.ipynb) that explains how to fine-tune the segmentation model. The steps to fine-tune the embedding model should be similar if you have reasons to believe that the speaker embeddings are not good for your use case.

In order to change the model in `OnlineSpeakerDiarization`, passing the string path or `Model` when creating the instance should take care of it : `pipeline = OnlineSpeakerDiarization(segmentation=Model.from_pretrained("/path/to/ckpt"), ...)`.

> for the second step, is there any way to process them?

Currently there is not. I recently created issue #53 for this as it's something that I would like diart to be capable of doing.
