### ISSUE TITLE
Question about changing model in system and real-time issue

### ISSUE THREAD

**Issue by Shoawen0213** [juanmc2005/StreamingSpeakerDiarization#58]
Hi @juanmc2005 ! it's me again, sorry for bothering you...
I have several questions
1. I have already fine-tuned a segmentation model with other dataset (not AIM, VoxConverse) and store in ".ckpt" model. I sure that it can be loaded by using 
`ckpt_path = "path/where/store/ckpt/epoch=9_best.ckpt"`
`Model.from_pretrained(ckpt_path, strict=False)` 
i want to put replace this model in your system for some testing. But when i change [here](https://github.com/juanmc2005/StreamingSpeakerDiarization/blob/e89472c63443c81ec95a2e8ddc22429669b053a2/src/diart/pipelines.py#L22) by `segmentation: PipelineModel = Model.from_pretrained('path/where/store/ckpt/epoch=9_best.ckpt')`. When using "python -m diart.stream", the system is still using "pyannote/segmentation". could you give me some hints?
2. Is there any useful augmentation method for training or fine-tuning? I know that can add back noise or something. Where should i add them? 
3. this system can use for real-time right (streaming)? If yes, how to confirm "real-time"? like real-time factor or something else?

Thanks for your awesome project, it helps me a lot!!
Looking forward to your reply~~
Best Regards

**Comment by juanmc2005** [comment]
Hi @Shoawen0213,

1) If you want to run your own pipeline, you should write a separate script and use diart's python API. Right now `diart.stream` does not support running custom pipelines (although this is something I'd like to add in the future).
I recently released version 0.3 where there's a new inference API. I would recommend you to start with the template from [here](https://github.com/juanmc2005/StreamingSpeakerDiarization#inference-api) and set the model in your `PipelineConfig` like this:

```python
my_model = Model.from_pretrained('path/to/model.ckpt')
pipeline = OnlineSpeakerDiarization(PipelineConfig(segmentation=my_model))
```

2) As an example, `pyannote/segmentation` is trained with additive background noise and impulse responses. You should do this while training. I recommend you take a look at [torch-audiomentations](https://github.com/asteroid-team/torch-audiomentations) from the asteroid team.

3) Yes, this is the main goal of the library. In order for your system to be able to actually run in real time you need to make sure that the real time latency (the processing time of an audio chunk) is lower than the step. For example if you send new chunks to the system every 500ms (step=0.5) and your real time latency is 1s, then chunks will accumulate faster than you are able to make predictions.
In the new inference API that I mentioned above, there's also a `Benchmark` class that allows you to measure the real-time latency of your pipeline (when you set batch_size=1).
For more info on `Benchmark` see [here](https://github.com/juanmc2005/StreamingSpeakerDiarization#reproducibility) and [here](https://github.com/juanmc2005/StreamingSpeakerDiarization/blob/main/src/diart/inference.py#L74).

I hope this answers your questions.
Don't hesitate to ask if the usage of the inference API is not clear.

**Comment by Shoawen0213** [comment]
Hi! @juanmc2005 , very much appreciate your reply!!
For question 1, i fix the problem and it seems that it can load my own segmentation model. I will try your recommendation.
In this part, I would like to ask for some advice. If i want to evaluate in my own dataset, I can fine-tune the segmentation model then put it into the pipeline(like mentioned above). In your opinion, do I need to fine-tune the embedding model ?

For question 2, i have seen [torch-audiomentations](https://github.com/asteroid-team/torch-audiomentations) before, but i'm not sure where to add it when doing training. could you give some hint or template in this situation?

For question 3, forgive my stupidity.
so, [here](https://github.com/juanmc2005/StreamingSpeakerDiarization/blob/e89472c63443c81ec95a2e8ddc22429669b053a2/src/diart/stream.py#L15) means "send new chunks to the system every 500ms (step=0.5) " and [here ](https://github.com/juanmc2005/StreamingSpeakerDiarization/blob/e89472c63443c81ec95a2e8ddc22429669b053a2/src/diart/stream.py#L16) means the real time latency?
I have read the paper several times in these several weeks. I'm still confused about these two meanings.
In my understanding, the rolling buffer is fix in "5s", right?
and the latency means to output the result every latency, which means, for example, if the latency is 3s, then the system will output the result every 3 seconds? or it means the chunk size?
Then i don;t know step means truly...
sorry for bothering...

I will try the Benchmark API after i clarify my confusion!!

Thank you for your guidance and support.
It is hard to find words to express my gratitude.

**Comment by juanmc2005** [comment]
> In your opinion, do I need to fine-tune the embedding model ?

I think this depends a lot on your specific application. If you have reasons to believe that the training domain of `pyannote/embedding` is considerably different of your target domain, then I'd suggest you fine-tune it as well. However, for most purposes `pyannote/embedding` should do fine.

Another reason you might want to train your own embedding model is if you can have a better one, although this might change the architecture and not necessarily be compatible with diart's default pipeline because the model needs to accept per-speaker weights. There was a similar discussion concerning speechbrain embeddings in #34.

> For question 2, i have seen [torch-audiomentations](https://github.com/asteroid-team/torch-audiomentations) before, but i'm not sure where to add it when doing training. could you give some hint or template in this situation?

This is about training, so not related to diart. I would suggest you ask this question in the pyannote.audio repo.

> so, [here](https://github.com/juanmc2005/StreamingSpeakerDiarization/blob/e89472c63443c81ec95a2e8ddc22429669b053a2/src/diart/stream.py#L15) means "send new chunks to the system every 500ms (step=0.5)"

Yes.

> and [here](https://github.com/juanmc2005/StreamingSpeakerDiarization/blob/e89472c63443c81ec95a2e8ddc22429669b053a2/src/diart/stream.py#L16) means the real time latency?

No. The system makes a prediction at every step (500ms), and the size of the input chunk is fixed (5s). What changes with the latency argument is the timestamp of the prediction.
This might be confusing because there are 2 different latencies in the pipeline.

The one that you mention here is the system latency. It answers to the question "at a current recording time `t`, for what **time in the recording** is the system giving me an answer?".
If the system is given a conversation chunk that goes from 5s to 10s, then `t=10`. If the latency is 3s, the output of the system is from `t - latency == 7s` to `t - latency + step == 7.5s`. When it moves to the next chunk (from 5.5s to 10.5s), the output will be from 7.5s to 8s.

The real-time latency is something entirely different and it is not set by the user. It answers to the question "how much **processing time** does it take (on a given CPU/GPU) for the system to calculate the prediction of a given chunk?".

While the former is a hyper-parameter set by the user, the latter is a property.
The system latency allows you to be more/less tolerant with delays in the answer, it plays with the perceived responsiveness on purpose to let the system have more information and make better predictions.
The real-time latency is affected by the machine in which you're running the algorithm (CPU and/or GPU), the inference time of both segmentation and embedding models, the complexity of clustering, etc.

**Comment by Shoawen0213** [comment]
Hi! @juanmc2005 Thanks for your clear reply for question 1 and I have opened an issue on pyannote.audio for question 2. 
Hope to have some answers or suggestion QAQ. 
For this part ↓
>If the system is given a conversation chunk that goes from 5s to 10s, then t=10. If the latency is 3s, the output of the system is from t - latency == 7s to t - latency + step == 7.5s. When it moves to the next chunk (from 5.5s to 10.5s), the output will be from 7.5s to 8s.

I still can't get it...I draw a figure and try to describe my understanding. Please correct me if i misunderstand anything!
 
![S__5505026](https://user-images.githubusercontent.com/63163334/171664809-955adcc4-b10c-40e3-a075-a9c896a48075.jpg)
From my understanding, there's an input chuck is fixed in 5s as input and it sent into the system every 0.5s, which means the system will get the duration of 5s per 0.5s ?
Then the system might contain a rolling buffer to store the input chunk (5s). 
as shown in the figure, if the latency is 3s and the step is 0.5s _(does this step the same as mentioned above?)_
then can i realize that the system will output the diart result at 7s to 7.5s to represent the result of the 5s to 5.5s audio in the buffer? And if the latency is set to 5, then the system will output the diart result at 5s to 5.5s to represent the result of the 5s to 5.5s audio in the buffer? 
Sorry for bothering and please forgive my stupidity.

**Comment by juanmc2005** [comment]
> From my understanding, there's an input chuck is fixed in 5s as input and it sent into the system every 0.5s, which means the system will get the duration of 5s per 0.5s ?

The system will receive 5s of audio every 500ms. Since it's a sliding window over the conversation (this is what we call a rolling buffer), chunk `i` will overlap the last 4.5s with the first 4.5s of chunk `i + 1`. This is depicted in Figure 4 of the paper.

> does this step the same as mentioned above?

Yes there is only one notion of step.

> then can i realize that the system will output the diart result at 7s to 7.5s to represent the result of the 5s to 5.5s audio in the buffer?

No, the timestamps of the input and the output are aligned, so an output for 7s-7.5s is a prediction for the same 7s-7.5s in the input audio.

> And if the latency is set to 5, then the system will output the diart result at 5s to 5.5s to represent the result of the 5s to 5.5s audio in the buffer?

Yes, because the current time `t` is 10s, so in order to understand what region of the input the output corresponds to you have to do the following:

```
output_start_time = t (10s) - latency (5s) = 5s
output_end_time = output_start_time + step (0.5s) = 5.5s
```

The duration of the output is always the size of the step, this is completely independent from the latency.
Notice that if you try different latencies in the formula above, it's as if you were "moving" the focus of the system at a given chunk. This is why lower latencies are more "responsive": the output window is closer to `t`, whereas a higher latency reduces the responsiveness by having a bigger delay in the prediction, i.e. the output window is farther away from `t`.
However, the latency can't exceed 5s (the chunk size) because it's out of the scope of the current chunk, making it essentially the same as a 5s latency. And it can't be lower than 0.5s (the step) either because a single update already includes 0.5s of audio, so getting closer to `t` would only make the system miss audio regions.

**Comment by Shoawen0213** [comment]
Gosh! I finally understand this part of this awesome project!!!!
Thanks for your clear and kind reply! Also appreciate your patience!
I'm very very grateful for your help!!

One more small question, the paper indicated that the system has the same performance as the official offline baseline of
the DIHARD III challenge by setting the latency as 3s(25.5% vs 25.4%). But why not said that the system can beat the official offline baseline when setting the latency as 4s or 5s? Are there any considerations?

**Comment by juanmc2005** [comment]
I'm glad it's clear now :)
At this point you should probably be able to understand quite a bit of diart's code, so if you ever think of some interesting feature or you find a bug, any contribution/pull request is more than welcome!

> But why not said that the system can beat the official offline baseline when setting the latency as 4s or 5s? Are there any considerations?

That is also shown, although not specifically written. I guess the takeaway from that sentence is that we succeed in obtaining the same performance with much lower requirements: low system latency, very low real-time latency (165ms on CPU), online processing, and with continual improvement.

**Comment by Shoawen0213** [comment]
Thanks for your clear reply!!
Very grateful for your help!!
I will try to understand more about diart's code!
If I have other questions about code or the paper, I will beg for your help again QQ

**Comment by Shoawen0213** [comment]
AH!!! I figure out that i forget to ask a simple question. 

> same performance with much lower requirements: low system latency, very low real-time latency **(165ms on CPU)**

for here, I saw that the paper indicates 165ms on CPU or 50ms on GPU. 
Does the diart code default using the GPU?

**Comment by juanmc2005** [comment]
In version 0.3 it defaults to GPU yes, both in the python API and `diart.stream`/`diart.inference`.
Adding `--cpu` when you run the script forces CPU usage.

**Comment by Shoawen0213** [comment]
@juanmc2005 Got it!! thanks for your answer~~
