### ISSUE TITLE
Question about Optuna

### ISSUE THREAD

**Issue by Shoawen0213** [juanmc2005/StreamingSpeakerDiarization#82]
hi, @juanmc2005  thanks for adding Optuna! 
I want to use it for tuning hyper-parameter
I follow the code
`from diart.optim import Optimizer, TauActive, RhoUpdate, DeltaNew`
`from diart.pipelines import PipelineConfig`
`from diart.inference import Benchmark`
`benchmark = Benchmark("/wav/dir", "/rttm/dir", "/out/dir/tmp", show_report=False)`
`base_config = PipelineConfig()`
`hparams = [TauActive, RhoUpdate, DeltaNew]`
`optimizer = Optimizer(benchmark, base_config, hparams, "/out/dir")`
`optimizer.optimize(num_iter=100, show_progress=True)`
In my realize, 
/wav/dir means the wav I want to evaluation
/rttm/dir means the reference rttm of wav, am I right?

When I follow the code above, the error is
![image](https://user-images.githubusercontent.com/63163334/187139523-165ea587-40e6-4636-88a1-ed0f33b9cabc.png)
I am trying to figure out what caused this problem, it seems that the rttm generated in the work directory are empy
show as figure 
![image](https://user-images.githubusercontent.com/63163334/187140285-6f3f020f-4345-42e7-bb57-a31d6abdfb8b.png)
What might be the reason caused this problem and how could i fix this?
Do i miss some step??

Thanks for your awesome work and help!!!

**Comment by juanmc2005** [comment]
Hi @Shoawen0213,

This is related to issue #80, which was fixed by @zaouk and is now in `develop`.

What I think is happening is that the hyper-parameters chosen by optuna are detecting 0 speakers in that run. Another (less likely) possibility is that your audio does not contain speech.

I suggest you try installing from the `develop` branch and run the optimization process again.
I'm planning to release version 0.5 soon with this fix and some other improvements.

Let me know if this solves your problem!

**Comment by Shoawen0213** [comment]
Hi @juanmc2005, Thanks for your suggestion! It works with your answer!
Thanks a lot!
