### ISSUE TITLE
Rolling buffer size / duration in fine-tune segmentation model 

### ISSUE THREAD

**Issue by Shoawen0213** [juanmc2005/StreamingSpeakerDiarization#97]
Hi! @juanmc2005  sorry for bothering you! It's me again!
I learned and understand a lot from your teaching in #58 before!
Recently I thought of a question, please forgive my bad memory if I asked

In your awesome work, I know that there's the rolling buffer in 5s, and here are two tunable parameters related to "step" and "latency".
SO~Does the rolling buffer size can be changed?
if i fine-tune the segmentation model like
`pretrained = Model.from_pretrained("pyannote/segmentation")`
`seg_task = Segmentation(callhomeSPK2, duration=10.0, max_num_speakers=2)`
Does the duration here mean the rolling buffer or something else?
Cause, after I fine-tune them and store them in ckpt file
it seems that it can be loaded with ` Model.from_pretrained(ckpt_path, strict=False)`
But as far as I know, it doesn't feel like it's possible to adjust simply by doing this.
That's why I came to ask for your teaching :)

And why i want to change the rolling buffer size is just because I suddenly thought of the paper I saw half a year ago,  Online end-to-end neural diarization with speaker-tracing buffer and Online streaming end-to-end neural diarization handling overlapping speech and flexible numbers of speakers, from Xue, Yawen.

So I'm wondering if it's possible to improve performance by upgrading the rolling buffer size.
Looking forward to your reply~~
Best Regards

**Comment by juanmc2005** [comment]
Hi @Shoawen0213,

Definitely! The duration of the rolling buffer can be changed in diart. If you fine-tune a `pyannote/segmentation` model with `duration=10.0` and you don't specify the duration in `PipelineConfig`, it should automatically choose the rolling buffer size to match the training duration.

Remember that `step <= latency <= duration`, so if you increase the duration you can also increase the latency.
However, I can think of two disadvantages of doing this:
1. You'll increase the real-time factor because getting an output will now be more costly
2. You'll probably have to use a coarser resolution to avoid having extremely long input sequences to the LSTM

I hope this makes sense, let me know what you think.

**Comment by Shoawen0213** [comment]
Hi! @juanmc2005, Thanks for your answer!!
I did some simple experiments increasing the buffer size, like 10 seconds and 20 seconds.
The RTF did not increase so significantly actually, but the result was indeed not as good as the original.
This makes me really curious why those two papers can be good with buffer size in the 50s, 100s

Again!
Thanks for your awesome work!!! It really helps me a lot indeed!
